# -*- coding: utf-8 -*-
"""Regroupement_FeatureEng.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aynm_wmM09gXkXFDVE5SIkMrUef66pw7
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor, AdaBoostRegressor, BaggingRegressor, StackingRegressor



# Pour concaténer les deux dataframes
def gather_data(df1,df2):
   data=pd.concat([df1,df2],ignore_index=True, axis=1)

   return data


# Pour le préprocessing

def feature_eng(dataset):

#Pour les variables catégorielles en choisissanthughbh f
   labelencoder = LabelEncoder()
   ordinalencoder = OrdinalEncoder()
   onehotencoder = OneHotEncoder()

#Pour les variables numériques
   minmaxscaler = MinMaxScaler()
   standardscaler = StandardScaler()

   for i in range(0,dataset.shape[1]):
        if type(dataset[0,i]) == str: 
          dataset.iloc[:,i] = labelencoder.fit_transform(dataset.iloc[:,i]) 
        else:  
          dataset.iloc[:,i] = minmaxscaler.fit_transform(dataset.iloc[:,i])


   return dataset